# Generated by Django 2.1.1 on 2018-09-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='model_pic',
            field=models.ImageField(default='blog/images/already.png', upload_to='blog/images'),
        ),
    ]
